### ISSUE TITLE
[Bug] With invalid hbs, prettier will transform `<template>` in source code

### ISSUE THREAD

**Issue by simonihmig** [gitKrystan/prettier-plugin-ember-template-tag#43]
### 🐞 Describe the Bug

When hbs inside `<template>` is invalid, prettier will transform `<template>` in the _source_ file to its internal representation format (`__GLIMMER_TEMPLATE()`)

### 🔬 Minimal Reproduction

1. In a .gts/.gjs test file, create a `<template>` tag that contains invalid hbs syntax, like this:

![image](https://user-images.githubusercontent.com/1325249/214049437-4ef4c041-4426-406b-bfd4-0ee7edd57522.png)

2. Run prettier on it

### 😕 Actual Behavior

![image](https://user-images.githubusercontent.com/1325249/214049584-b0adc698-4667-4f79-b408-036efe3ec828.png)

### 🤔 Expected Behavior

No reformatting happens, `<template>` is not transformed.

### 🌍 Environment

- prettier-plugin-ember-template-tag version: 0.3.0
- ember-template-imports version: 3.4.0

**Comment by gitKrystan** [comment]
Thanks for the report! I'm currently swamped with another project but I will look into this ASAP.

In the meantime, if you (or someone else following along) have time, could you add a test following [these instructions](https://github.com/gitKrystan/prettier-plugin-ember-template-tag/blob/main/CONTRIBUTING.md#tests) and link here?

With regular JS/TS, when there is a syntax error, Prettier appears to be a no-op but will log an error.
Because this library has to pre-process GTS into JS/TS `([__GLIMMER_TEMPLATE(...)]` before running the regular Prettier parser/printer flow, it must trigger an error somewhere that causes the printer to not to convert back to GTS from TS.

If you have time you could see if this throws an error we can catch: https://github.com/gitKrystan/prettier-plugin-ember-template-tag/blob/main/src/print/template.ts#L32

**Comment by simonihmig** [comment]
Thanks for the references! I'll see if I can work on this next week!

**Comment by gitKrystan** [comment]
Thanks. Prettier swallows errors pretty aggressively, so I am hoping we can find something somewhere to catch!

**Comment by gitKrystan** [comment]
@simonihmig I released a quick fix for this. It's still a little broken in that it seems to add a new new-line after every save (https://github.com/gitKrystan/prettier-plugin-ember-template-tag/issues/49). 😂 But this is way less annoying than the original de-sugaring bug, and I'm out of time for fixing stuff on this library this week, so I shipped it. 🚀

**Comment by jurgenwerk** [comment]
I'm still getting this error using `prettier-plugin-ember-template-tag` version `0.3.2` in vscode that runs prettier on save.

I can reproduce it by pasting invalid code into `<template></template>` tag. If I paste "invalid code" in the tag, the following happens: 

<img width="759" alt="image" src="https://user-images.githubusercontent.com/273660/230591117-65b828bf-9973-412d-902b-8940a98deef0.png">

**Comment by gitKrystan** [comment]
> I'm still getting this error using `prettier-plugin-ember-template-tag` version `0.3.2` in vscode that runs prettier on save.

Thanks for the report. Unfortunately, I am unable to reproduce this issue with 0.3.2. Can you answer the following questions for me?

1. Did you recently upgrade to 0.3.2? If so, can you try reloading the VSCode window to see if it's just using the wrong version?
1. Are you running prettier on save directly or via an eslint fix?
1. Does this happen with _all_ invalid code? Can you provide an example of invalid code that causes this issue?
1. What versions are you running of: `ember-template-imports` and `prettier`. What is the output of `yarn why prettier-plugin-ember-template-tag` (or the equivalent for your package manager)?

**Comment by jurgenwerk** [comment]
@gitKrystan thanks for your reply. Here's my info:

1. No, 0.3.2 was present at the start of when I set up an existing project. I have reloaded vscode several times.
2. I'm running the following config for both javascript and typescript:
```
"[javascript]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
```
3. Actually, it happens whenever I paste anything, even valid code:
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/273660/232477694-b8f97a07-bbdb-4045-bdb5-cccefa24704c.png">

4. `ember-template-imports` is `3.0.1` and `prettier` is `2.7.1`. The output of `pnpm why prettier-plugin-ember-template-tag` is: 

```
devDependencies:
prettier-plugin-ember-template-tag 0.3.2
```

**Comment by gitKrystan** [comment]
> Actually, it happens whenever I paste anything, even valid code

@jurgenwerk Unfortunately, I'm still unable to reproduce, so I have. few more questions:

Do you have `"editor.formatOnPaste": true` set anywhere? I'm confused about why it's formatting on paste at all (let alone formatting incorrectly).

Does `updating ember-template-imports` and/or `prettier` to the latest version fix your issue?

Do any of the fixes suggested in Issue #38 help you?

**Comment by jurgenwerk** [comment]
@gitKrystan yes, I had `formatOnPaste` set to true. I switched it to `false` (I don't really need that feature) and that solved my issue. Thanks for your help!
